---
chdir: "/workspaces/sinatra-test-app"
environment: development
address: 0.0.0.0
port: 4567
timeout: 30
log: "/workspaces/sinatra-test-app/log/thin.log"
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
threaded: true
threadpool_size: 20
daemonize: true
